# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'MIEMApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MIEMApp
  #pod 'Alamofire', '~> 5.2'
  pod 'Alamofire'
  #pod 'GoogleSignIn'
  pod 'GoogleSignIn', '~> 5.0'
  pod 'EzPopup'
  pod 'AppAuth'
  pod 'BEMCheckBox'
  pod "TinyConstraints"
  pod 'Charts'



end
